name: CI

on: [ push, pull_request ]

jobs:
  industrial_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - { ROS_DISTRO: humble, ROS_REPO: testing }
          - { ROS_DISTRO: humble, ROS_REPO: main }
    name: ROS ${{ matrix.ROS_DISTRO }} (${{ matrix.ROS_REPO }})
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
  
